### ISSUE TITLE
Hints als je beste woord een 'vreemd' woord is

### ISSUE THREAD

**Issue by dvleeuwen99** [glorang/semantle-nl-php#2]
De hint die je krijgt is (deels) gebaseerd op wat op dat moment je beste woord is, mijn beste bestaande woord was 987/1000, maar had een vreemd woord daarboven, hint die ik nu telkens krijg is 500/1000, ook als ik herhaaldelijk op hint druk.

**Comment by glorang** [comment]
Bedankt voor het melden. Is gefixt!
